# Generated by Django 5.1 on 2026-02-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GateCore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='facial_recognition_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='phone_device_type',
            field=models.CharField(blank=True, choices=[('android', 'Android'), ('ios', 'iOS'), ('feature', 'Feature Phone'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='phone_otp',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='person',
            name='phone_otp_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
