# Generated by Django for AuditTrail model
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings

class Migration(migrations.Migration):
    dependencies = [
        ('GateCore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32, choices=[
                    ("move", "Move/Reallocate Person"),
                    ("link", "Link Person to Unit"),
                    ("unlink", "Unlink Person from Unit"),
                    ("edit", "Edit Person"),
                    ("create", "Create Person"),
                    ("update_unit", "Edit Unit"),
                    ("create_unit", "Create Unit"),
                    ("delete_unit", "Delete Unit"),
                ])),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.TextField(blank=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_trails', to='GateCore.person')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_trails', to='GateCore.unit')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'verbose_name': 'Audit Trail',
                'verbose_name_plural': 'Audit Trails',
            },
        ),
    ]
