# Generated by Django 5.1 on 2026-02-04 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GateCore', '0002_person_facial_recognition_enabled_and_more'),
        ('GateCore', '0003_audittrail'),
    ]

    operations = [
    ]
