# Generated by Django 5.1 on 2026-02-04 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GateCore', '0004_merge_20260204_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulerule',
            name='days_allowed',
            field=models.CharField(choices=[('weekdays', 'Weekdays'), ('workdays', 'Workdays'), ('weekends', 'Weekends'), ('custom', 'Custom')], default='weekdays', max_length=20),
        ),
        migrations.AddField(
            model_name='schedulerule',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schedulerule',
            name='notify_resident',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedulerule',
            name='pin',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='schedulerule',
            name='reason',
            field=models.CharField(choices=[('guest', 'Guest'), ('delivery', 'Delivery'), ('maintenance', 'Maintenance'), ('contractor', 'Contractor'), ('family', 'Family'), ('other', 'Other')], default='guest', max_length=30),
        ),
        migrations.AddField(
            model_name='schedulerule',
            name='reason_other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='schedulerule',
            name='schedule_kind',
            field=models.CharField(choices=[('preclearance', 'Preclearance'), ('schedule', 'Schedule')], default='schedule', max_length=20),
        ),
        migrations.AddField(
            model_name='schedulerule',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_rules', to='GateCore.unit'),
        ),
        migrations.AddField(
            model_name='schedulerule',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_schedules', to='GateCore.person'),
        ),
        migrations.AddField(
            model_name='schedulerule',
            name='visitor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='schedulerule',
            name='visitor_full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='schedulerule',
            name='visitor_mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='audittrail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
