# Generated by Django 4.2.28 on 2026-02-05 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GateCore', '0006_blacklist_is_active_schedulerule_recur_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('person', 'Person'), ('vehicle', 'Vehicle')], max_length=10)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('action', models.CharField(choices=[('blocked', 'Blocked'), ('unblocked', 'Unblocked')], max_length=10)),
                ('reason', models.TextField()),
                ('actioned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-actioned_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('license_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(db_index=True)),
                ('vehicle_codes', models.JSONField(blank=True, default=list)),
                ('vehicle_restrictions', models.JSONField(blank=True, default=list)),
                ('license_code_issue_dates', models.JSONField(blank=True, default=list)),
                ('driver_restriction_codes', models.CharField(blank=True, max_length=10)),
                ('prdp_codes', models.JSONField(blank=True, default=list)),
                ('prdp_expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('expired', 'Expired'), ('blocked', 'Blocked')], default='valid', max_length=10)),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='DriverVehicleAssociation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('total_visits', models.IntegerField(default=0)),
                ('is_primary_driver', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RawScanArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('driving_license', 'Driving License'), ('vehicle_disk', 'Vehicle Registration Disk')], max_length=30)),
                ('source_device', models.CharField(max_length=100)),
                ('scan_time', models.DateTimeField(auto_now_add=True)),
                ('raw_json', models.JSONField()),
                ('sha256_hash', models.CharField(db_index=True, max_length=64)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-scan_time'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('authorized_pins', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleRegistration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('plate_number', models.CharField(db_index=True, max_length=20)),
                ('vehicle_register_number', models.CharField(blank=True, max_length=20)),
                ('disk_number', models.CharField(max_length=50, unique=True)),
                ('expiry_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('expired', 'Expired'), ('blocked', 'Blocked')], default='valid', max_length=10)),
            ],
            options={
                'ordering': ['-expiry_date'],
            },
        ),
        migrations.AddField(
            model_name='accesslog',
            name='access_method',
            field=models.CharField(blank=True, choices=[('pin', 'PIN'), ('voice', 'Voice Clearance'), ('manual', 'Manual Override'), ('rfid', 'RFID Card'), ('biometric', 'Biometric'), ('qr', 'QR Code')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='entry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs_operated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='pin_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='GateCore.vehicle'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='visit_purpose',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='visiting_freeform',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='voice_clearance_granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_clearances_granted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='voice_clearance_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='block_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='block_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='colour',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='result',
            field=models.CharField(choices=[('granted', 'Granted'), ('denied', 'Denied'), ('expired', 'Expired'), ('expired_license', 'Expired License/Disk'), ('blocked', 'Blocked Entity'), ('invalid', 'Invalid Credential'), ('scheduled', 'Outside Schedule'), ('limit', 'Daily Limit Exceeded'), ('blacklisted', 'Blacklisted'), ('error', 'System Error')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('car', 'Car'), ('motorcycle', 'Motorcycle'), ('truck', 'Truck'), ('van', 'Van'), ('bus', 'Bus'), ('bicycle', 'Bicycle')], default='car', max_length=30),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['vehicle', 'entry_time'], name='GateCore_ac_vehicle_263257_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['access_point', 'entry_time'], name='GateCore_ac_access__14786a_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['entry_time'], name='GateCore_ac_entry_t_e0260d_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['exit_time'], name='GateCore_ac_exit_ti_8c50ef_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vin'], name='GateCore_ve_vin_50df9b_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_blocked', 'is_active'], name='GateCore_ve_is_bloc_fd1cdf_idx'),
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='raw_scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_registrations', to='GateCore.rawscanarchive'),
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='GateCore.vehicle'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenant',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenant',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='GateCore.unit'),
        ),
        migrations.AddIndex(
            model_name='rawscanarchive',
            index=models.Index(fields=['document_type', 'scan_time'], name='GateCore_ra_documen_84cdf0_idx'),
        ),
        migrations.AddIndex(
            model_name='rawscanarchive',
            index=models.Index(fields=['sha256_hash'], name='GateCore_ra_sha256__c262ec_idx'),
        ),
        migrations.AddField(
            model_name='drivervehicleassociation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drivervehicleassociation',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drivervehicleassociation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_vehicle_associations', to='GateCore.person'),
        ),
        migrations.AddField(
            model_name='drivervehicleassociation',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_associations', to='GateCore.vehicle'),
        ),
        migrations.AddField(
            model_name='driverlicense',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverlicense',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverlicense',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='GateCore.person'),
        ),
        migrations.AddField(
            model_name='driverlicense',
            name='raw_scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_licenses', to='GateCore.rawscanarchive'),
        ),
        migrations.AddField(
            model_name='blockhistory',
            name='actioned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='visiting_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_logs', to='GateCore.tenant'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['visiting_tenant'], name='GateCore_ac_visitin_0bc803_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleregistration',
            index=models.Index(fields=['vehicle', 'status'], name='GateCore_ve_vehicle_ef8ddc_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleregistration',
            index=models.Index(fields=['plate_number'], name='GateCore_ve_plate_n_4f51bc_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleregistration',
            index=models.Index(fields=['disk_number'], name='GateCore_ve_disk_nu_2aad35_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleregistration',
            index=models.Index(fields=['expiry_date', 'status'], name='GateCore_ve_expiry__75da84_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['unit', 'is_active'], name='GateCore_te_unit_id_9a8a92_idx'),
        ),
        migrations.AddIndex(
            model_name='drivervehicleassociation',
            index=models.Index(fields=['person', 'last_seen'], name='GateCore_dr_person__528b29_idx'),
        ),
        migrations.AddIndex(
            model_name='drivervehicleassociation',
            index=models.Index(fields=['vehicle', 'last_seen'], name='GateCore_dr_vehicle_f8a860_idx'),
        ),
        migrations.AddIndex(
            model_name='drivervehicleassociation',
            index=models.Index(fields=['is_primary_driver'], name='GateCore_dr_is_prim_f5b1f5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='drivervehicleassociation',
            unique_together={('person', 'vehicle')},
        ),
        migrations.AddIndex(
            model_name='driverlicense',
            index=models.Index(fields=['person', 'status'], name='GateCore_dr_person__7fa8ee_idx'),
        ),
        migrations.AddIndex(
            model_name='driverlicense',
            index=models.Index(fields=['expiry_date', 'status'], name='GateCore_dr_expiry__33e329_idx'),
        ),
        migrations.AddIndex(
            model_name='driverlicense',
            index=models.Index(fields=['license_number'], name='GateCore_dr_license_fe6d2d_idx'),
        ),
        migrations.AddIndex(
            model_name='blockhistory',
            index=models.Index(fields=['entity_type', 'entity_id'], name='GateCore_bl_entity__f5c56f_idx'),
        ),
        migrations.AddIndex(
            model_name='blockhistory',
            index=models.Index(fields=['actioned_at'], name='GateCore_bl_actione_30b01a_idx'),
        ),
    ]
