# Generated by Django 6.0.2 on 2026-02-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GateCore', '0006_blacklist_is_active_schedulerule_recur_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='barcode_hex',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='raw_scan_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='scan_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
