# Generated by Django 4.2.28 on 2026-02-05 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GateCore', '0007_blockhistory_driverlicense_drivervehicleassociation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='colour',
        ),
    ]
