# Generated by Django 6.0.2 on 2026-02-12 17:11

import GateCore.models.access
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GateCore', '0008_schedule_rule_preclearance_entry_flag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulerule',
            name='pin',
            field=models.CharField(blank=True, max_length=10, validators=[GateCore.models.access.validate_schedule_pin]),
        ),
        migrations.CreateModel(
            name='SystemPreclearanceConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('key', models.CharField(default='system-preclearance', max_length=50, unique=True)),
                ('qr_base64', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('last_rotated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('schedule_rule', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_preclearance_config', to='GateCore.schedulerule')),
            ],
            options={
                'ordering': ['-last_rotated'],
            },
        ),
    ]
