# Generated by Django 6.0.2 on 2026-02-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GateCore', '0009_alter_schedulerule_pin_systempreclearanceconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='systempreclearanceconfig',
            name='trigger_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
