# Generated by Django 6.0.2 on 2026-02-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GateCore', '0010_systempreclearanceconfig_trigger_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='permissions',
            field=models.CharField(choices=[('residence_basic', 'Residence-Basic'), ('residence_advanced', 'Residence - Advanced'), ('security', 'Security'), ('amenities', 'Amenities')], default='residence_basic', max_length=32),
        ),
    ]
