# Generated by Django 6.0.2 on 2026-02-26 18:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GateCore', '0015_accesslog_photo_files'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSDeliveryLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('trigger', models.CharField(blank=True, max_length=80)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('attempt', 'Attempt'), ('success', 'Success'), ('failure', 'Failure')], default='attempt', max_length=20)),
                ('recipient_phone', models.CharField(blank=True, max_length=30)),
                ('recipient_name', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField()),
                ('provider_message_id', models.CharField(blank=True, max_length=120)),
                ('error_message', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('visitor_name', models.CharField(blank=True, max_length=120)),
                ('visitor_phone', models.CharField(blank=True, max_length=30)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_delivery_logs', to='GateCore.person')),
                ('schedule_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_delivery_logs', to='GateCore.schedulerule')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_delivery_logs', to='GateCore.unit')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='GateCore_sm_status_709a42_idx'), models.Index(fields=['provider', 'created_at'], name='GateCore_sm_provide_dc3ab1_idx'), models.Index(fields=['recipient_phone'], name='GateCore_sm_recipie_afbc5d_idx'), models.Index(fields=['trigger'], name='GateCore_sm_trigger_12cb22_idx')],
            },
        ),
    ]
