# Generated by Django 6.0.2 on 2026-02-28 02:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GateCore', '0016_smsdeliverylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AndroidApp',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=100)),
                ('device_identifier', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('device_token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('device_model', models.CharField(blank=True, max_length=200)),
                ('device_os', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='android_apps', to='GateCore.group')),
            ],
            options={
                'verbose_name': 'Android App',
                'verbose_name_plural': 'Android Apps',
                'ordering': ['name', '-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='GroupAccessPermission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('schedule_override', models.JSONField(blank=True, default=dict)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('max_daily_uses', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=1)),
                ('access_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='GateCore.accesspoint')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_permissions', to='GateCore.group')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('schedule_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_permissions', to='GateCore.schedulerule')),
            ],
            options={
                'verbose_name': 'Group Access Permission',
                'verbose_name_plural': 'Group Access Permissions',
                'ordering': ['-priority', 'group'],
            },
        ),
        migrations.CreateModel(
            name='UnitGroupMembership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_memberships', to='GateCore.group')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='GateCore.unit')),
            ],
            options={
                'verbose_name': 'Unit Group Membership',
                'verbose_name_plural': 'Unit Group Memberships',
                'ordering': ['group', 'unit'],
            },
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['name', 'is_active'], name='GateCore_gr_name_7bdd5b_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['code'], name='GateCore_gr_code_36cda5_idx'),
        ),
        migrations.AddIndex(
            model_name='androidapp',
            index=models.Index(fields=['device_identifier'], name='GateCore_an_device__873073_idx'),
        ),
        migrations.AddIndex(
            model_name='androidapp',
            index=models.Index(fields=['device_token'], name='GateCore_an_device__1aa5e4_idx'),
        ),
        migrations.AddIndex(
            model_name='androidapp',
            index=models.Index(fields=['group', 'is_active'], name='GateCore_an_group_i_51fdad_idx'),
        ),
        migrations.AddIndex(
            model_name='groupaccesspermission',
            index=models.Index(fields=['group', 'is_active'], name='GateCore_gr_group_i_adcf60_idx'),
        ),
        migrations.AddIndex(
            model_name='groupaccesspermission',
            index=models.Index(fields=['access_point', 'valid_until'], name='GateCore_gr_access__e04427_idx'),
        ),
        migrations.AddIndex(
            model_name='groupaccesspermission',
            index=models.Index(fields=['valid_until', 'is_active'], name='GateCore_gr_valid_u_834009_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupaccesspermission',
            unique_together={('group', 'access_point')},
        ),
        migrations.AddIndex(
            model_name='unitgroupmembership',
            index=models.Index(fields=['unit', 'is_active'], name='GateCore_un_unit_id_f473f8_idx'),
        ),
        migrations.AddIndex(
            model_name='unitgroupmembership',
            index=models.Index(fields=['group', 'is_active'], name='GateCore_un_group_i_6cd37f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unitgroupmembership',
            unique_together={('unit', 'group')},
        ),
    ]
