# Generated by Django 6.0.2 on 2026-02-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GateCore', '0017_group_androidapp_groupaccesspermission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='grants_workflow_access',
            field=models.BooleanField(default=False, help_text='If True, people in units in this group get Operator (workflow) role on mobile login.'),
        ),
    ]
