# Generated by Django 6.0.2 on 2026-02-28 06:43

import GateCore.models.people
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GateCore', '0018_add_grants_workflow_access_to_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=30, unique=True, validators=[GateCore.models.people.validate_phone_number]),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['phone'], name='GateCore_pe_phone_b8f70d_idx'),
        ),
    ]
