# Generated by Django 6.0.2 on 2026-03-19 15:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GateCore', '0019_person_phone_unique_and_normalize'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RuntimeSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('key', models.CharField(default='global', max_length=32, unique=True)),
                ('pin_length', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(8)])),
                ('allow_sip_calls', models.BooleanField(default=True)),
                ('send_visitor_sms', models.BooleanField(default=True)),
                ('send_visitor_sms_otp', models.BooleanField(default=True)),
                ('send_visitor_sms_exitcode', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Runtime setting',
                'verbose_name_plural': 'Runtime settings',
                'ordering': ['-modified_at'],
            },
        ),
    ]
