# Generated by Django 6.0.2 on 2026-03-19 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GateCore', '0020_runtimesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtimesettings',
            name='anti_passback_allow_manual_override',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='runtimesettings',
            name='anti_passback_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='runtimesettings',
            name='anti_passback_enforce_no_reentry_without_exit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='runtimesettings',
            name='anti_passback_override_comment_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='runtimesettings',
            name='anti_passback_warning_message',
            field=models.CharField(default='Anti-passback: no valid entry in last 24 hours', max_length=255),
        ),
        migrations.AddField(
            model_name='runtimesettings',
            name='anti_passback_window_hours',
            field=models.PositiveSmallIntegerField(default=24, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(72)]),
        ),
    ]
