# Generated by Django 6.0.2 on 2026-03-21 08:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GateCore', '0027_person_photo_review_attempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GateTerminal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('serial_number', models.CharField(max_length=120, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('direction', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit'), ('both', 'Entry & Exit')], default='entry', max_length=10)),
                ('docking_mode', models.CharField(choices=[('local_cloud_platform', 'Local Cloud Platform'), ('local_software', 'Local Software'), ('developer', 'Developer'), ('offline', 'Offline')], default='local_cloud_platform', max_length=32)),
                ('server_url', models.URLField(blank=True)),
                ('server_port', models.PositiveIntegerField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=60)),
                ('app_version', models.CharField(blank=True, max_length=60)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=32)),
                ('sync_cursor', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['display_name', 'serial_number'],
            },
        ),
        migrations.AddField(
            model_name='gateterminal',
            name='access_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_terminals', to='GateCore.accesspoint'),
        ),
        migrations.AddField(
            model_name='gateterminal',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_gate_terminals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gateterminal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gateterminal',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gateterminal',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_terminals', to='GateCore.site'),
        ),
        migrations.AddIndex(
            model_name='gateterminal',
            index=models.Index(fields=['serial_number'], name='GateCore_ga_serial__279267_idx'),
        ),
        migrations.AddIndex(
            model_name='gateterminal',
            index=models.Index(fields=['approval_status', 'last_seen_at'], name='GateCore_ga_approva_28c174_idx'),
        ),
        migrations.AddIndex(
            model_name='gateterminal',
            index=models.Index(fields=['site', 'direction'], name='GateCore_ga_site_id_1580a8_idx'),
        ),
    ]
