# Generated by Django 6.0.2 on 2026-03-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GateCore', '0028_gateterminal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='card_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='person',
            name='face_access_password',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='person',
            name='face_effective_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='face_max_pass_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='face_pass_count_cycle',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='face_pass_rule_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='person',
            name='face_tts_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='person',
            name='face_user_type',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
