# Generated by Django 6.0.2 on 2026-03-23 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GateCore', '0029_rename_gatecore_devic_device_i_3dca81_idx_gatecore_de_device__8703c1_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devicesyncjob',
            new_name='GateCore_de_device__8703c1_idx',
            old_name='GateCore_devic_device_i_3dca81_idx',
        ),
        migrations.RenameIndex(
            model_name='devicesyncjob',
            new_name='GateCore_de_last_st_426868_idx',
            old_name='GateCore_devic_last_st_6c5bd2_idx',
        ),
        migrations.AlterField(
            model_name='audittrail',
            name='action',
            field=models.CharField(choices=[('move', 'Move/Reallocate Person'), ('link', 'Link Person to Unit'), ('unlink', 'Unlink Person from Unit'), ('edit', 'Edit Person'), ('create', 'Create Person'), ('face_enroll', 'Enroll Face'), ('face_enroll_failed', 'Face Enrollment Failed'), ('update_unit', 'Edit Unit'), ('create_unit', 'Create Unit'), ('delete_unit', 'Delete Unit')], max_length=32),
        ),
        migrations.AlterField(
            model_name='devicesyncjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='devicesyncjob',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
