# Generated by Django 6.0.2 on 2026-03-24 08:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GateCore', '0031_facereference_faceverificationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorFaceAccessGrant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('entry_pass_used', models.BooleanField(default=False)),
                ('exit_pass_used', models.BooleanField(default=False)),
                ('entry_used_at', models.DateTimeField(blank=True, null=True)),
                ('exit_used_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('active', 'Active'), ('expired', 'Expired'), ('completed', 'Completed'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('entry_terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_entry_face_grants', to='GateCore.gateterminal')),
                ('exit_terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_exit_face_grants', to='GateCore.gateterminal')),
                ('guest_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_access_grants', to='GateCore.guestregistration')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_face_access_grants', to='GateCore.person')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'valid_until'], name='GateCore_vi_status_14241b_idx'), models.Index(fields=['person', 'status'], name='GateCore_vi_person__a1f7cc_idx'), models.Index(fields=['guest_registration', 'status'], name='GateCore_vi_guest_r_7a0cde_idx')],
            },
        ),
    ]
