# Generated by Django 6.0.2 on 2026-02-10 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DummyDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DummySite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('access_point_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('devices', models.ManyToManyField(related_name='access_points', to='frontend.dummydevice')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_points', to='frontend.dummysite')),
            ],
        ),
    ]
