# Redirect unauthenticated users to the Django admin login, which is the
# active login entry point exposed by this project.
LOGIN_URL = '/admin/login/'
# Celery configuration: use Redis broker by default
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
# Django REST Framework basic settings for testing
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}
PHONE_OTP_EXPIRATION_MINUTES = 5
SMS_GATEWAY_PROVIDER = "stouf"  # options: console, infobip, stouf
SEND_SMS_PASSWORD = "cl0uds311"
SEND_SMS_URL = "http://ws.stouf.com/StoufSMS/SMSService.asmx"
SEND_SMS_USERNAME = "ws_cloudsell"
SEND_SMS_APP_NAME = "ws_cloudsell"
SEND_SMS_DEFAULT_COUNTRY_CODE = "27"
SEND_SMS_WITH_PIN_FOR_ADHOC = True
SEND_SMS_ENFORCE_LOGGED_PATH = True
SEND_SMS_ALLOWED_TRIGGERS = [
    "entry_workflow_sms",
    "mobile_login_otp",
    "preclearance_entry_pin",
]
SMS_PORTAL_API_SECRET = "e1477921-4547-4440-b4d9-61759563fa16"
SMS_PORTAL_CLIENT_ID = "18834566-4dd2-40fa-80fb-fb529ab19c4f"
SMS_GATEWAY_CONFIG = {
    "infobip": {
        "base_url": "https://api.infobip.com/sms/2/text/advanced",
        "api_key": "",
        "sender": "AccessCtrl",
    },
    "stouf": {
        "endpoint": SEND_SMS_URL,
        "username": SEND_SMS_USERNAME,
        "password": SEND_SMS_PASSWORD,
        "sender": "AccessCtrl",
    },
}
EXPOSE_PHONE_OTP = True
"""
Django settings for AccessControll project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env from backend directory so TWILIO_* and other secrets stay out of code.
# python-dotenv is optional; if it is not installed, fall back to a tiny local parser.
def _load_env_file(path: Path) -> None:
    if not path.exists():
        return
    try:
        for raw_line in path.read_text(encoding="utf-8").splitlines():
            line = raw_line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            if key and key not in os.environ:
                os.environ[key] = value
    except Exception:
        pass

try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / ".env")
except ImportError:
    _load_env_file(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-txa=fb43+6i5tus%iwn!vgkg^1*mxl$x90r8dk#rq6%)9wvyl7'
VOIP_WEBHOOK_SECRET = os.environ.get("VOIP_WEBHOOK_SECRET", "")
import sys as _sys
_repo_sh = BASE_DIR / "scripts" / "asterisk" / "voip_originate_call.sh"
if _sys.platform == "win32":
    _default_voip_script = str(BASE_DIR / "scripts" / "asterisk" / "voip_originate_call_wsl.bat")
else:
    _default_voip_script = str(_repo_sh) if _repo_sh.exists() else "/usr/local/bin/voip_originate_call.sh"
VOIP_ORIGINATE_SCRIPT = os.environ.get("VOIP_ORIGINATE_SCRIPT", _default_voip_script)
VOIP_ASTERISK_TRUNK = os.environ.get("VOIP_ASTERISK_TRUNK", "vphone-trunk")
# Asterisk AMI settings (for status + provisioning + originate)
ASTERISK_HOST = os.environ.get("ASTERISK_HOST", "")
ASTERISK_AMI_PORT = int(os.environ.get("ASTERISK_AMI_PORT", "5038"))
ASTERISK_AMI_USER = os.environ.get("ASTERISK_AMI_USER", "admin")
ASTERISK_AMI_SECRET = os.environ.get("ASTERISK_AMI_SECRET", "admin")
ASTERISK_CONTEXT = os.environ.get("ASTERISK_CONTEXT", "from-internal")
# File Asterisk will be written to when auto-provisioning PJSIP entries via AMI.
# Prefer a custom include to avoid editing core config directly.
ASTERISK_PJSIP_AUTOGEN_FILE = os.environ.get("ASTERISK_PJSIP_AUTOGEN_FILE", "pjsip_custom.conf")
# "local" = resident's phone rings directly. Any extension value rings that PBX endpoint first.
# Default to local so mobile calls don't depend on a registered desk extension.
VOIP_INTERCOM_CALLER_ENDPOINT = os.environ.get("VOIP_INTERCOM_CALLER_ENDPOINT", "local")
VOIP_CALL_INITIATE_SYNC = os.environ.get("VOIP_CALL_INITIATE_SYNC", "1").lower() in ("1", "true", "yes", "on")
# Outbound voice: "asterisk" (SIP/VoIP) or "twilio". Default asterisk so Twilio is not used unless explicitly enabled.
VOIP_ENGINE = (os.environ.get("VOIP_ENGINE", "asterisk") or "asterisk").lower().strip()

# Twilio (trial or paid) for outbound voice calls. Only used when VOIP_ENGINE=twilio.
# Auth: use either TWILIO_AUTH_TOKEN OR both TWILIO_API_KEY_SID + TWILIO_API_KEY_SECRET
TWILIO_ACCOUNT_SID = os.environ.get("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN = os.environ.get("TWILIO_AUTH_TOKEN", "")
TWILIO_API_KEY_SID = os.environ.get("TWILIO_API_KEY_SID", "")
TWILIO_API_KEY_SECRET = os.environ.get("TWILIO_API_KEY_SECRET", "")
TWILIO_VOICE_FROM_NUMBER = os.environ.get("TWILIO_VOICE_FROM_NUMBER", "")  # E.164, e.g. +15551234567
# Base URL Twilio can reach for voice webhooks (e.g. https://your-server.com or https://xxx.ngrok.io for local)
TWILIO_VOICE_WEBHOOK_BASE_URL = os.environ.get("TWILIO_VOICE_WEBHOOK_BASE_URL", "").rstrip("/")

# CompreFace face enrollment configuration
COMPREFACE_BASE_URL = os.environ.get("COMPREFACE_BASE_URL", "").rstrip("/")
COMPREFACE_API_KEY = os.environ.get("COMPREFACE_API_KEY", "")
COMPREFACE_DETECTION_API_KEY = os.environ.get("COMPREFACE_DETECTION_API_KEY", "")
COMPREFACE_VERIFICATION_API_KEY = os.environ.get("COMPREFACE_VERIFICATION_API_KEY", "")
COMPREFACE_RECOGNITION_FACES_PATH = os.environ.get("COMPREFACE_RECOGNITION_FACES_PATH", "/api/v1/recognition/faces/")
COMPREFACE_TIMEOUT_SECONDS = int(os.environ.get("COMPREFACE_TIMEOUT_SECONDS", "30"))
VISITOR_FACE_ENROLLMENT_URL_BASE = os.environ.get("VISITOR_FACE_ENROLLMENT_URL_BASE", "http://192.168.0.2:8001/visitor/face-enrollment/").strip()
PERSON_PHOTO_MIN_QUALITY_SCORE = int(os.environ.get("PERSON_PHOTO_MIN_QUALITY_SCORE", "85"))
PUBLIC_VISITOR_FACE_MIN_QUALITY_SCORE = int(os.environ.get("PUBLIC_VISITOR_FACE_MIN_QUALITY_SCORE", "70"))
PERSON_PHOTO_MATCH_THRESHOLD = float(os.environ.get("PERSON_PHOTO_MATCH_THRESHOLD", "90")) / 100.0
PERSON_PHOTO_SPOOF_REVIEW_THRESHOLD = int(os.environ.get("PERSON_PHOTO_SPOOF_REVIEW_THRESHOLD", "45"))
PERSON_PHOTO_SPOOF_REJECT_THRESHOLD = int(os.environ.get("PERSON_PHOTO_SPOOF_REJECT_THRESHOLD", "70"))
PERSON_PHOTO_DEBUG_SAVE = os.environ.get("PERSON_PHOTO_DEBUG_SAVE", "0").lower() in ("1", "true", "yes", "on")
PERSON_PHOTO_CROP_RATIO = float(os.environ.get("PERSON_PHOTO_CROP_RATIO", "0.72"))
PERSON_PHOTO_CROP_TOP_BIAS = float(os.environ.get("PERSON_PHOTO_CROP_TOP_BIAS", "0.20"))
GATE_DEVICE_SYNC_TOKEN = os.environ.get("GATE_DEVICE_SYNC_TOKEN", "")
MOBILE_REMOTE_QR_ENABLED = os.environ.get("MOBILE_REMOTE_QR_ENABLED", "0").lower() in ("1", "true", "yes", "on")

# Face verification update thresholds (0-100 scale)
FACE_VERIFICATION_THRESHOLD = float(os.environ.get("FACE_VERIFICATION_THRESHOLD", "90.0"))
FACE_REVIEW_THRESHOLD = float(os.environ.get("FACE_REVIEW_THRESHOLD", "90.0"))
FACE_UPDATE_RATE_LIMIT = int(os.environ.get("FACE_UPDATE_RATE_LIMIT", "3"))  # max attempts per hour
FACE_REVIEW_EXPIRY_HOURS = int(os.environ.get("FACE_REVIEW_EXPIRY_HOURS", "48"))

# Show voip INFO logs in console (e.g. VOIP CALL SUCCESS when resident presses 9)
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "voip_console": {
            "format": "[%(levelname)s] %(name)s: %(message)s",
        },
    },
    "handlers": {
        "console_voip": {
            "class": "logging.StreamHandler",
            "formatter": "voip_console",
            "stream": "ext://sys.stdout",
        },
    },
    "loggers": {
        "voip": {
            "handlers": ["console_voip"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

if DEBUG:
    SECURE_CROSS_ORIGIN_OPENER_POLICY = None

ALLOWED_HOSTS = ["*"]

# Added example tokens for preclearance device authentication
PRECLEARANCE_DEVICE_TOKENS = [
    "example-token-1",
    "example-token-2",
    "example-token-3"
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'drf_yasg',
    'workflows',
    'accounts',
    'frontend',
    'GateCore',
    'face_devices',
    'voip',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AccessControll.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'frontend' / 'templates'],
        'APP_DIRS': True,  # CRITICAL for 3rd party templates
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AccessControll.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# CORS configuration
CORS_ALLOW_ALL_ORIGINS = True
