# Generated by Django 6.0.2 on 2026-03-21 14:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GateCore', '0029_rename_gatecore_devic_device_i_3dca81_idx_gatecore_de_device__8703c1_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceDeviceAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('device_identifier', models.CharField(db_index=True, max_length=200)),
                ('action', models.CharField(choices=[('ping', 'Ping'), ('pull_settings', 'Pull Settings'), ('pull_user_count', 'Pull User Count'), ('pull_user_ids', 'Pull User IDs'), ('sync_users', 'Sync Users'), ('add_user', 'Add User'), ('delete_user', 'Delete User'), ('delete_all_users', 'Delete All Users'), ('reboot', 'Reboot Device')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error'), ('timeout', 'Timeout')], db_index=True, default='pending', max_length=20)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_device_actions_requested', to=settings.AUTH_USER_MODEL)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_device_actions', to='GateCore.gateterminal')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device_identifier', 'created_at'], name='face_device_device__3fd9c9_idx'), models.Index(fields=['action', 'created_at'], name='face_device_action_7c674f_idx'), models.Index(fields=['status', 'created_at'], name='face_device_status_ae4547_idx')],
            },
        ),
        migrations.CreateModel(
            name='FaceDeviceEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('device_identifier', models.CharField(db_index=True, max_length=200)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=20)),
                ('command', models.CharField(db_index=True, max_length=120)),
                ('status', models.CharField(choices=[('received', 'Received'), ('sent', 'Sent'), ('success', 'Success'), ('error', 'Error')], default='received', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('remote_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('event_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('error', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_device_events', to='GateCore.gateterminal')),
            ],
            options={
                'ordering': ['-event_time', '-created_at'],
                'indexes': [models.Index(fields=['device_identifier', 'event_time'], name='face_device_device__922d28_idx'), models.Index(fields=['command', 'event_time'], name='face_device_command_5ea0ce_idx'), models.Index(fields=['status', 'event_time'], name='face_device_status_fb0584_idx')],
            },
        ),
    ]
