# Generated by Django 6.0.2 on 2026-03-21 15:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GateCore', '0029_rename_gatecore_devic_device_i_3dca81_idx_gatecore_de_device__8703c1_idx_and_more'),
        ('face_devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceDeviceAccessLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('device_identifier', models.CharField(db_index=True, max_length=200)),
                ('source_command', models.CharField(blank=True, db_index=True, max_length=120)),
                ('event_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('deny', 'Deny'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('snapshot_image', models.ImageField(blank=True, null=True, upload_to='face_devices/snapshots/')),
                ('panoramic_image', models.ImageField(blank=True, null=True, upload_to='face_devices/panoramic/')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('remote_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_device_access_logs', to='GateCore.person')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_device_access_logs', to='GateCore.gateterminal')),
            ],
            options={
                'ordering': ['-event_time', '-created_at'],
                'indexes': [models.Index(fields=['device_identifier', 'event_time'], name='face_device_device__299d6e_idx'), models.Index(fields=['result', 'event_time'], name='face_device_result_15296c_idx'), models.Index(fields=['source_command', 'event_time'], name='face_device_source__0f172d_idx')],
            },
        ),
    ]
