# Generated by Django 6.0.2 on 2026-03-21 16:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GateCore', '0029_rename_gatecore_devic_device_i_3dca81_idx_gatecore_de_device__8703c1_idx_and_more'),
        ('face_devices', '0002_facedeviceaccesslog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceDeviceUserState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('device_identifier', models.CharField(db_index=True, max_length=200)),
                ('user_identifier', models.CharField(db_index=True, max_length=200)),
                ('state', models.CharField(choices=[('present', 'Present On Device'), ('missing', 'Missing On Device'), ('unexpected', 'Unexpected On Device'), ('stale', 'Stale')], db_index=True, max_length=20)),
                ('last_seen_on_device_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_device_user_states', to='GateCore.person')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_device_user_states', to='GateCore.gateterminal')),
            ],
            options={
                'ordering': ['user_identifier'],
                'indexes': [models.Index(fields=['device_identifier', 'state'], name='face_device_device__10e2c1_idx'), models.Index(fields=['user_identifier', 'state'], name='face_device_user_id_c8ef00_idx')],
                'constraints': [models.UniqueConstraint(fields=('device_identifier', 'user_identifier'), name='face_device_user_state_unique_device_user')],
            },
        ),
    ]
