# Generated by Django 6.0.2 on 2026-03-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_devices', '0003_facedeviceuserstate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facedeviceaction',
            options={'ordering': ['-created_at'], 'permissions': [('can_run_destructive_face_device_actions', 'Can run destructive face device actions')]},
        ),
    ]
